BEGIN;
CREATE TABLE IF NOT EXISTS cars (
	Id SERIAL PRIMARY KEY,
	Owner INTEGER REFERENCES users (Id) NOT NULL,
	RegNum CHARACTER VARYING(9) NOT NULL,
	Mark CHARACTER VARYING(255) NOT NULL,
	Model CHARACTER VARYING(255) NOT NULL,
	Year INTEGER
);
COMMIT;