{{- if and .Values.ingress.tls.enabled (and .Values.tls.crt .Values.tls.key) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt | quote }}
  tls.key: {{ .Values.tls.key | quote }}
{{- end }}
